 # Bài Tập 2:
 1.Import thư viện:

In [1]:
import pandas as pd
import pylab as pl
import numpy as np
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt


 2.Read data from `csv` file

In [2]:
df_Cont = pd.read_csv("ML_Learning_Hobby.csv")
df_Cont.head()


X    Y
0  60  Yes
1  55   No
2  61   No
3  70  Yes
4  59  Yes

In [3]:
X = np.asarray(df_Cont[['X']])
X[0:5]


array([[60],
       [55],
       [61],
       [70],
       [59]], dtype=int64)

 3. Chuyển Feature `y` từ `Yes` thành `1` và `No` thành `0`

In [4]:
LE_y = preprocessing.LabelEncoder()
LE_y.fit(['No','Yes'])
df_Cont['Y'] = LE_y.transform(df_Cont['Y'].values.reshape(-1,1))
df_Cont['Y'].head()


0    1
1    0
2    0
3    1
4    1
Name: Y, dtype: int32

In [5]:
y = np.asarray(df_Cont[['Y']])
y[0:5]


array([[1],
       [0],
       [0],
       [1],
       [1]])

In [6]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression().fit(X, y)
LR


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
X_new = 62
yhat = LR.predict([[X_new]])
yhat


array([1])

 Với `X_new` = `62` kg thì sinh viên này thích học machine learning

 # Bài tập 3
 ## Xây dựng mô hình hồi quy logistic dựa vào nhóm các thuộc tích liên tục FeatureName_Cont.

 1.Read data from `csv` file

In [8]:
df_Cont = pd.read_csv("Play_Tennis.csv")
df_Cont.head()



Day Outlook_Cat  Outlook_Cont Temp_Cat  Temp_Cont Humidity_Cat  \
0    1       Sunny            15      Hot         36         High   
1    2       Sunny            17      Hot         35         High   
2    3    Overcast            57      Hot         30         High   
3    4        Rain            90     Mild         26         High   
4    5        Rain            92     Cool         25       Normal   

   Humidity_Cont Wind_Cat  Wind_Cont Play_Tennis  
0             71     Weak        0.5          No  
1             80   Strong        4.0          No  
2             75     Weak        0.7         Yes  
3             73     Weak        0.8         Yes  
4             61     Weak        1.0         Yes

 2. Chuyển Feature `y` từ `Yes` thành `1` và `No` thành `0`

In [9]:
LE_y = preprocessing.LabelEncoder()
LE_y.fit(['No','Yes'])
df_Cont['Play_Tennis'] = LE_y.transform(df_Cont['Play_Tennis'].values.reshape(-1,1))
df_Cont['Play_Tennis'].head()



0    0
1    0
2    1
3    1
4    1
Name: Play_Tennis, dtype: int32

In [10]:
X = np.asarray(df_Cont[["Outlook_Cont", "Temp_Cont", "Humidity_Cont", "Wind_Cont"]])
X[0:5]


array([[15. , 36. , 71. ,  0.5],
       [17. , 35. , 80. ,  4. ],
       [57. , 30. , 75. ,  0.7],
       [90. , 26. , 73. ,  0.8],
       [92. , 25. , 61. ,  1. ]])

In [11]:
y = np.asarray(df_Cont[["Play_Tennis"]])
y[0:5]


array([[0],
       [0],
       [1],
       [1],
       [1]])

In [12]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression().fit(X, y)
LR


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
yhat = LR.predict(X)
yhat

# # %%
# from sklearn.metrics import classification_report
# print(classification_report(y, yhat))

# # %%
# X_new = np.linspace(0, 3, 1000).reshape(-1, 1)
# y_proba = LR.predict_proba(X_new)
# plt.plot(X_new, y_proba[:, 1], "g-", label="Iris-Virginica")
# plt.show()

# # %%


array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1])

 ## Xây dựng mô hình hồi quy logistic dựa vào nhóm các thuộc tích liên tục FeatureName_Cont và rời rạc FeatureName_Cat

In [14]:
df_All = df_Cont.copy()
df_All.head()


Day Outlook_Cat  Outlook_Cont Temp_Cat  Temp_Cont Humidity_Cat  \
0    1       Sunny            15      Hot         36         High   
1    2       Sunny            17      Hot         35         High   
2    3    Overcast            57      Hot         30         High   
3    4        Rain            90     Mild         26         High   
4    5        Rain            92     Cool         25       Normal   

   Humidity_Cont Wind_Cat  Wind_Cont  Play_Tennis  
0             71     Weak        0.5            0  
1             80   Strong        4.0            0  
2             75     Weak        0.7            1  
3             73     Weak        0.8            1  
4             61     Weak        1.0            1

In [15]:
df_All.pivot_table(index =['Outlook_Cat'], aggfunc='size')



Outlook_Cat
Overcast    4
Rain        5
Sunny       5
dtype: int64

In [16]:
LE_Outlook_Cat = preprocessing.LabelEncoder()
LE_Outlook_Cat.fit(["Overcast", "Rain", "Sunny"])
df_All["Outlook_Cat"] = LE_Outlook_Cat.transform(df_All['Outlook_Cat'].values.reshape(-1,1))
df_All["Outlook_Cat"].head()


0    2
1    2
2    0
3    1
4    1
Name: Outlook_Cat, dtype: int32

In [17]:
df_All.pivot_table(index =['Temp_Cat'], aggfunc='size')


Temp_Cat
Cool    4
Hot     4
Mild    6
dtype: int64

In [18]:
LE_Temp_Cat = preprocessing.LabelEncoder()
LE_Temp_Cat.fit(["Cool", "Mild", "Hot"])
df_All["Temp_Cat"] = LE_Temp_Cat.transform(df_All['Temp_Cat'].values.reshape(-1,1))
df_All["Temp_Cat"].head()



0    1
1    1
2    1
3    2
4    0
Name: Temp_Cat, dtype: int32

In [19]:
df_All.pivot_table(index =['Humidity_Cat'], aggfunc='size')


Humidity_Cat
High      7
Normal    7
dtype: int64

In [20]:
LE_Humidity_Cat = preprocessing.LabelEncoder()
LE_Humidity_Cat.fit(["High", "Normal"])
df_All["Humidity_Cat"] = LE_Humidity_Cat.transform(df_All['Humidity_Cat'].values.reshape(-1,1))
df_All["Humidity_Cat"].head()



0    0
1    0
2    0
3    0
4    1
Name: Humidity_Cat, dtype: int32

In [21]:
df_All.pivot_table(index =['Wind_Cat'], aggfunc='size')


Wind_Cat
Strong    6
Weak      8
dtype: int64

In [22]:
LE_Wind_Cat = preprocessing.LabelEncoder()
LE_Wind_Cat.fit(["Strong", "Weak"])
df_All["Wind_Cat"] = LE_Wind_Cat.transform(df_All['Wind_Cat'].values.reshape(-1,1))
df_All["Wind_Cat"].head()


0    1
1    0
2    1
3    1
4    1
Name: Wind_Cat, dtype: int32

In [23]:
X_All = np.asarray(df_All[["Outlook_Cat", "Outlook_Cont", "Temp_Cat", "Temp_Cont", "Humidity_Cat", "Humidity_Cont", "Wind_Cat", "Wind_Cont"]])
X_All[0:5]



array([[ 2. , 15. ,  1. , 36. ,  0. , 71. ,  1. ,  0.5],
       [ 2. , 17. ,  1. , 35. ,  0. , 80. ,  0. ,  4. ],
       [ 0. , 57. ,  1. , 30. ,  0. , 75. ,  1. ,  0.7],
       [ 1. , 90. ,  2. , 26. ,  0. , 73. ,  1. ,  0.8],
       [ 1. , 92. ,  0. , 25. ,  1. , 61. ,  1. ,  1. ]])

In [24]:
y_All = np.asarray(df_All[["Play_Tennis"]])
y_All[0:5]


array([[0],
       [0],
       [1],
       [1],
       [1]])

In [25]:
from sklearn.linear_model import LogisticRegression
LR_All = LogisticRegression().fit(X_All, y_All)
LR_All


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
yhat_All = LR_All.predict(X_All)
yhat_All


array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0])

 ## Đánh giá:
 Classification Report của model chỉ có FeatureName_Cont

In [27]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y, yhat))


precision    recall  f1-score   support

           0       0.33      0.20      0.25         5
           1       0.64      0.78      0.70         9

    accuracy                           0.57        14
   macro avg       0.48      0.49      0.48        14
weighted avg       0.53      0.57      0.54        14



 Classification Report của model có FeatureName_Cont và FeatureName_Cat

In [28]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_All, yhat_All))


precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.80      0.89      0.84         9

    accuracy                           0.79        14
   macro avg       0.78      0.74      0.75        14
weighted avg       0.78      0.79      0.78        14



 Ta thấy accuracy tăng khi ta kết hợp nhóm các thuộc tích liên tục FeatureName_Cont và rời rạc FeatureName_Cat