### Bài tập 1.
 - <ins>Yêu cầu</ins>: Trình bày sự khác biệt cơ bản của mô hình hồi quy tuyến tính và mô hình hồi quy logistic.

# 1. Kết quả của Linear Regression là các giá trị tuyến tính còn với logistic Regression là các giá trị rời rạc
# 2. Để sử dụng Linear Regression chúng ta cần một mối quan hệ tuyến tính giữa các giá trị của các biến độc lập và không độc lập còn logistic Regression không cần điều này
# 3. Linear Regression sử dụng đường thẳng để dự đoán kết quả trong khi đó logistic sử dụng đường cong cho dữ liệu
# 4. Linear Regression thì dành cho các bài toán hồi quy tuyến tính còn logistic thì dành cho các bài toán phân loại 
# 5. Linear Regression sử dụng hàm gausses để phân phối giả định cho các biến độc lập trong khi logistic Regression sử dụng phân phối nhị thức


### Bài tập 2.

|    |   X | Y   |
|---:|----:|:----|
|  0 |  60 | Yes |
|  1 |  55 | No  |
|  2 |  61 | No  |
|  3 |  70 | Yes |
|  4 |  59 | Yes |
|  5 |  65 | Yes |
|  6 |  80 | Yes |
|  7 |  63 | No  |
|  8 |  50 | No  |
|  9 |  75 | Yes |
| 10 |  73 | Yes |
| 11 |  51 | No  |

- <ins>Mô tả</ins>: Bài toán dự đoán sở thích học Machine Learning thông qua số đo cân nặng.
- <ins>Dữ liệu</ins>: Tập tin ``ML_Learning_Hobby.csv``.
- <ins>Yêu cầu</ins>:
    - Xây dựng mô hình hồi quy logistic (sử dụng thư viện có sẵn hoặc ``build from scratch`` đều được) với thuộc tính tự do là ``X`` (cân nặng, là biến liên tục) và thuộc tính phụ thuộc ``Y`` (chỉ có hai giá trị ``Yes`` và ``No``, là biến rời rạc).
    - Dự đoán rằng sinh viên có cân nặng ``X_new`` = ``62`` kg có thích học môn Machine Learning hay không?

In [194]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
import matplotlib.pyplot as plt 

In [195]:
data = pd.read_csv('ML_Learning_Hobby.csv')
data 

X    Y
0   60  Yes
1   55   No
2   61   No
3   70  Yes
4   59  Yes
5   65  Yes
6   80  Yes
7   63   No
8   50   No
9   75  Yes
10  73  Yes
11  51   No

In [196]:
X = data['X']
X = np.array(X)
X = np.reshape(X, (-1,1))
X

array([[60],
       [55],
       [61],
       [70],
       [59],
       [65],
       [80],
       [63],
       [50],
       [75],
       [73],
       [51]], dtype=int64)

In [197]:
y = data['Y']
y = np.array(y)
y = np.reshape(y, (-1, 1))
y

array([['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No']], dtype=object)

In [198]:
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)
y = np.reshape(y, (-1, 1))
y

array([[1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0]])

In [199]:
log_reg = LogisticRegression()
log_reg.fit(X,y)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [200]:
X_new = np.array([62])
X_new = np.reshape(X_new, (-1, 1))
y_new = log_reg.predict(X_new)
y_new

array([1])

### Bài tập 3.

|    |   Day | Outlook_Cat   |   Outlook_Cont | Temp_Cat   |   Temp_Cont | Humidity_Cat   |   Humidity_Cont | Wind_Cat   |   Wind_Cont | Play_Tennis   |
|---:|------:|:--------------|---------------:|:-----------|------------:|:---------------|----------------:|:-----------|------------:|:--------------|
|  0 |     1 | Sunny         |             15 | Hot        |          36 | High           |              71 | Weak       |         0.5 | No            |
|  1 |     2 | Sunny         |             17 | Hot        |          35 | High           |              80 | Strong     |         4   | No            |
|  2 |     3 | Overcast      |             57 | Hot        |          30 | High           |              75 | Weak       |         0.7 | Yes           |
|  3 |     4 | Rain          |             90 | Mild       |          26 | High           |              73 | Weak       |         0.8 | Yes           |
|  4 |     5 | Rain          |             92 | Cool       |          25 | Normal         |              61 | Weak       |         1   | Yes           |
|  5 |     6 | Rain          |             91 | Cool       |          23 | Normal         |              50 | Strong     |         3   | No            |
|  6 |     7 | Overcast      |             60 | Cool       |          25 | Normal         |              52 | Strong     |         4   | Yes           |
|  7 |     8 | Sunny         |              8 | Mild       |          27 | High           |              65 | Weak       |         0.9 | No            |
|  8 |     9 | Sunny         |             10 | Cool       |          20 | Normal         |              53 | Weak       |         1   | Yes           |
|  9 |    10 | Rain          |             95 | Mild       |          27 | Normal         |              52 | Weak       |         1.1 | Yes           |
| 10 |    11 | Sunny         |              7 | Mild       |          29 | Normal         |              57 | Strong     |         3.5 | Yes           |
| 11 |    12 | Overcast      |             49 | Mild       |          28 | High           |              66 | Strong     |         7   | Yes           |
| 12 |    13 | Overcast      |             62 | Hot        |          31 | Normal         |              57 | Weak       |         0.5 | Yes           |
| 13 |    14 | Rain          |             94 | Mild       |          28 | High           |              66 | Strong     |         6   | No            |


- <ins>Mô tả</ins>: Tìm mô hình hồi quy trên tập dữ liệu huấn luyện bao gồm các thuộc tính ``Outlook``, ``Temp``, ``Humidity``, ``Wind`` để dự đoán thuộc tính ``Play_Tennis``.
- <ins>Dữ liệu</ins>: Tập tin ``Play_Tennis.csv``.
- <ins>Lưu ý</ins>: Mỗi thuộc tính đã nêu ở phần mô tả sẽ có hai cột dữ liệu rời rạc và liên tục. Cụ thể là ``Outlook`` sẽ được biểu diễn bởi ``Outlook_Cat`` (Categorical Feature) và ``Outlook_Cont`` (Continuous Variable), và tương tự cho các thuộc tính còn lại. Thuộc tính ``Play_Tennis`` chỉ có hai giá trị rời rạc ``Yes`` và ``No``.
- <ins>Yêu cầu</ins>:
    - Xây dựng mô hình hồi quy logistic dựa vào nhóm các thuộc tích liên tục ``FeatureName_Cont``.
    - Xây dựng mô hình hồi quy logistic dựa vào nhóm các thuộc tích liên tục ``FeatureName_Cont`` và rời rạc ``FeatureName_Cat`` (có thể sử dụng thư viện ``LabelEncoder`` để  chuyển thuộc tính rời rạc sang liên tục).
    - Nhận xét kết quả đạt được từ hai mô hình.

In [201]:
data = pd.read_csv('Play_Tennis.csv')
data

Day Outlook_Cat  Outlook_Cont Temp_Cat  Temp_Cont Humidity_Cat  \
0     1       Sunny            15      Hot         36         High   
1     2       Sunny            17      Hot         35         High   
2     3    Overcast            57      Hot         30         High   
3     4        Rain            90     Mild         26         High   
4     5        Rain            92     Cool         25       Normal   
5     6        Rain            91     Cool         23       Normal   
6     7    Overcast            60     Cool         25       Normal   
7     8       Sunny             8     Mild         27         High   
8     9       Sunny            10     Cool         20       Normal   
9    10        Rain            95     Mild         27       Normal   
10   11       Sunny             7     Mild         29       Normal   
11   12    Overcast            49     Mild         28         High   
12   13    Overcast            62      Hot         31       Normal   
13   14        Rain            94     Mild         28         High   

    Humidity_Cont Wind_Cat  Wind_Cont Play_Tennis  
0              71     Weak        0.5          No  
1              80   Strong        4.0          No  
2              75     Weak        0.7         Yes  
3              73     Weak        0.8         Yes  
4              61     Weak        1.0         Yes  
5              50   Strong        3.0          No  
6              52   Strong        4.0         Yes  
7              65     Weak        0.9          No  
8              53     Weak        1.0         Yes  
9              52     Weak        1.1         Yes  
10             57   Strong        3.5         Yes  
11             66   Strong        7.0         Yes  
12             57     Weak        0.5         Yes  
13             66   Strong        6.0          No

In [202]:
X_1 = data [["Outlook_Cont", "Temp_Cont", "Humidity_Cont", "Wind_Cont"]]

In [203]:
X_1

Outlook_Cont  Temp_Cont  Humidity_Cont  Wind_Cont
0             15         36             71        0.5
1             17         35             80        4.0
2             57         30             75        0.7
3             90         26             73        0.8
4             92         25             61        1.0
5             91         23             50        3.0
6             60         25             52        4.0
7              8         27             65        0.9
8             10         20             53        1.0
9             95         27             52        1.1
10             7         29             57        3.5
11            49         28             66        7.0
12            62         31             57        0.5
13            94         28             66        6.0

In [204]:
y = data["Play_Tennis"].copy()
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [219]:
log_reg =LogisticRegression(multi_class="multinomial",solver="lbfgs", C=10)
log_reg.fit(X_1, y)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [220]:
y_predict_1 = log_reg.predict(X_1)

In [221]:
y_predict_1 

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [208]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

# Độ chính xác là 0.71

In [209]:
X_2 = data.drop("Play_Tennis", axis = 1)
X_2

Day Outlook_Cat  Outlook_Cont Temp_Cat  Temp_Cont Humidity_Cat  \
0     1       Sunny            15      Hot         36         High   
1     2       Sunny            17      Hot         35         High   
2     3    Overcast            57      Hot         30         High   
3     4        Rain            90     Mild         26         High   
4     5        Rain            92     Cool         25       Normal   
5     6        Rain            91     Cool         23       Normal   
6     7    Overcast            60     Cool         25       Normal   
7     8       Sunny             8     Mild         27         High   
8     9       Sunny            10     Cool         20       Normal   
9    10        Rain            95     Mild         27       Normal   
10   11       Sunny             7     Mild         29       Normal   
11   12    Overcast            49     Mild         28         High   
12   13    Overcast            62      Hot         31       Normal   
13   14        Rain            94     Mild         28         High   

    Humidity_Cont Wind_Cat  Wind_Cont  
0              71     Weak        0.5  
1              80   Strong        4.0  
2              75     Weak        0.7  
3              73     Weak        0.8  
4              61     Weak        1.0  
5              50   Strong        3.0  
6              52   Strong        4.0  
7              65     Weak        0.9  
8              53     Weak        1.0  
9              52     Weak        1.1  
10             57   Strong        3.5  
11             66   Strong        7.0  
12             57     Weak        0.5  
13             66   Strong        6.0

In [210]:
X_2["Outlook_Cat"]

0        Sunny
1        Sunny
2     Overcast
3         Rain
4         Rain
5         Rain
6     Overcast
7        Sunny
8        Sunny
9         Rain
10       Sunny
11    Overcast
12    Overcast
13        Rain
Name: Outlook_Cat, dtype: object

In [211]:
le = preprocessing.LabelEncoder()
le.fit(X_2["Outlook_Cat"])
X_2["Outlook_Cat"] = le.transform(X_2["Outlook_Cat"])

In [212]:
X_2

Day  Outlook_Cat  Outlook_Cont Temp_Cat  Temp_Cont Humidity_Cat  \
0     1            2            15      Hot         36         High   
1     2            2            17      Hot         35         High   
2     3            0            57      Hot         30         High   
3     4            1            90     Mild         26         High   
4     5            1            92     Cool         25       Normal   
5     6            1            91     Cool         23       Normal   
6     7            0            60     Cool         25       Normal   
7     8            2             8     Mild         27         High   
8     9            2            10     Cool         20       Normal   
9    10            1            95     Mild         27       Normal   
10   11            2             7     Mild         29       Normal   
11   12            0            49     Mild         28         High   
12   13            0            62      Hot         31       Normal   
13   14            1            94     Mild         28         High   

    Humidity_Cont Wind_Cat  Wind_Cont  
0              71     Weak        0.5  
1              80   Strong        4.0  
2              75     Weak        0.7  
3              73     Weak        0.8  
4              61     Weak        1.0  
5              50   Strong        3.0  
6              52   Strong        4.0  
7              65     Weak        0.9  
8              53     Weak        1.0  
9              52     Weak        1.1  
10             57   Strong        3.5  
11             66   Strong        7.0  
12             57     Weak        0.5  
13             66   Strong        6.0

In [213]:
le = preprocessing.LabelEncoder()
le.fit(data["Temp_Cat"])
X_2["Temp_Cat"] = le.transform(X_2["Temp_Cat"])
X_2

Day  Outlook_Cat  Outlook_Cont  Temp_Cat  Temp_Cont Humidity_Cat  \
0     1            2            15         1         36         High   
1     2            2            17         1         35         High   
2     3            0            57         1         30         High   
3     4            1            90         2         26         High   
4     5            1            92         0         25       Normal   
5     6            1            91         0         23       Normal   
6     7            0            60         0         25       Normal   
7     8            2             8         2         27         High   
8     9            2            10         0         20       Normal   
9    10            1            95         2         27       Normal   
10   11            2             7         2         29       Normal   
11   12            0            49         2         28         High   
12   13            0            62         1         31       Normal   
13   14            1            94         2         28         High   

    Humidity_Cont Wind_Cat  Wind_Cont  
0              71     Weak        0.5  
1              80   Strong        4.0  
2              75     Weak        0.7  
3              73     Weak        0.8  
4              61     Weak        1.0  
5              50   Strong        3.0  
6              52   Strong        4.0  
7              65     Weak        0.9  
8              53     Weak        1.0  
9              52     Weak        1.1  
10             57   Strong        3.5  
11             66   Strong        7.0  
12             57     Weak        0.5  
13             66   Strong        6.0

In [214]:
le = preprocessing.LabelEncoder()
le.fit(data["Humidity_Cat"])
X_2["Humidity_Cat"] = le.transform(X_2["Humidity_Cat"])
X_2

Day  Outlook_Cat  Outlook_Cont  Temp_Cat  Temp_Cont  Humidity_Cat  \
0     1            2            15         1         36             0   
1     2            2            17         1         35             0   
2     3            0            57         1         30             0   
3     4            1            90         2         26             0   
4     5            1            92         0         25             1   
5     6            1            91         0         23             1   
6     7            0            60         0         25             1   
7     8            2             8         2         27             0   
8     9            2            10         0         20             1   
9    10            1            95         2         27             1   
10   11            2             7         2         29             1   
11   12            0            49         2         28             0   
12   13            0            62         1         31             1   
13   14            1            94         2         28             0   

    Humidity_Cont Wind_Cat  Wind_Cont  
0              71     Weak        0.5  
1              80   Strong        4.0  
2              75     Weak        0.7  
3              73     Weak        0.8  
4              61     Weak        1.0  
5              50   Strong        3.0  
6              52   Strong        4.0  
7              65     Weak        0.9  
8              53     Weak        1.0  
9              52     Weak        1.1  
10             57   Strong        3.5  
11             66   Strong        7.0  
12             57     Weak        0.5  
13             66   Strong        6.0

In [215]:
le = preprocessing.LabelEncoder()
le.fit(data["Wind_Cat"])
X_2["Wind_Cat"] = le.transform(X_2["Wind_Cat"])
X_2

Day  Outlook_Cat  Outlook_Cont  Temp_Cat  Temp_Cont  Humidity_Cat  \
0     1            2            15         1         36             0   
1     2            2            17         1         35             0   
2     3            0            57         1         30             0   
3     4            1            90         2         26             0   
4     5            1            92         0         25             1   
5     6            1            91         0         23             1   
6     7            0            60         0         25             1   
7     8            2             8         2         27             0   
8     9            2            10         0         20             1   
9    10            1            95         2         27             1   
10   11            2             7         2         29             1   
11   12            0            49         2         28             0   
12   13            0            62         1         31             1   
13   14            1            94         2         28             0   

    Humidity_Cont  Wind_Cat  Wind_Cont  
0              71         1        0.5  
1              80         0        4.0  
2              75         1        0.7  
3              73         1        0.8  
4              61         1        1.0  
5              50         0        3.0  
6              52         0        4.0  
7              65         1        0.9  
8              53         1        1.0  
9              52         1        1.1  
10             57         0        3.5  
11             66         0        7.0  
12             57         1        0.5  
13             66         0        6.0

In [222]:
log_reg = LogisticRegression(multi_class="multinomial",solver="lbfgs", C=10)
log_reg.fit(X_2, y)
y_predict_2 = log_reg.predict(X_2)
y_predict_2

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [223]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

# Độ chính xác gần như hoàn toàn